apiVersion: v1
kind: Pod
metadata:
 name: env
spec:
  containers:
    - name: nginx
      image: nginx
      env:
      - name: course
        valueFrom:
          configMapKeyRef:
            name: course-data
            key: course
      - name: trainer
        valueFrom:
          configMapKeyRef:
            name: course-data
            key: duration